routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {

    return view('index');
})->name('login');

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/login', 'LoginController@login');
Route::post('/logout', 'LoginController@logout')->name('logout');

Route::resource('User/orderh', 'OrderHeaderCRUDController');
Route::resource('User/orderd', 'OrderDetailCRUDController');
Route::resource('User/expenditure', 'ExpenditureCRUDController');
Route::resource('User/inventory', 'InventoryCRUDController');
Route::resource('User/customer', 'CustomerCRUDController');

Route::get('User/orderd/create/{id}','OrderDetailCRUDController@createOrderD')->name('orderd.create.orderd');
Route::post('User/orderd/store/{id}','OrderDetailCRUDController@storeOrderD')->name('orderd.store.orderd');
Route::get('User/orderd/edit/{id_order_h}/{orderd}','OrderDetailCRUDController@editOrderD')->name('orderd.edit.orderd');
Route::patch('User/orderd/update/{id_order_h}/{orderd}','OrderDetailCRUDController@updateOrderD')->name('orderd.update.orderd');
Route::delete('User/orderd/destroy/{id_order_h}/{orderd}','OrderDetailCRUDController@destroyOrderD')->name('orderd.destroy.orderd');
Route::post('User/pdf','PDFController@pdf')->name('pdf');
Route::get('User/recap','PDFController@index')->name('recap');
Route::get('User/orderd/index/{id}','OrderDetailCRUDController@indexOrderD')->name('orderd.index.orderd');
Route::post('User/orderd/index/{id}','OrderDetailCRUDController@indexOrderD')->name('orderd.index.orderd');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Customer extends Model
{
	protected $table = "customer";
    protected $fillable = ['id','name','contact'];
    public $timestamps = false;
    // protected $dates = ['date'];

}

?>

resources/views/Customers/add.blade.php
@extends('layouts.sidebar')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" />
@endsection

@section('section')
<section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>
                    TRANSACTIONS
                    
                </h2>
            </div>
            
            <!-- Advanced Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>EDIT INVENTORY</h2>
                            
                        </div>
                        <div class="body">
                            <form action="{{ route('customer.store') }}" enctype="multipart/form-data" method="post"> 
                 
                                {{ csrf_field() }}
                                
                                
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="name" id="name"  minlength="5" maxlength="191" required>
                                        <label class="form-label">Name</label>
                                    </div>
                                    <div class="help-info">Min. 5 characters</div>
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span><br>
                                    @endif
                                </div>

                                

                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="contact" id="contact"  minlength="5" maxlength="191" required>
                                        <label class="form-label">Added by</label>
                                    </div>
                                    <div class="help-info">Min. 5 characters</div>
                                    @if ($errors->has('contact'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('contact') }}</strong>
                                        </span><br>
                                    @endif
                                </div>
                                
                                
                                
                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Advanced Validation -->
            
        </div>
    </section>

@endsection

@section('script')

   <!-- Jquery Core Js -->
    <script src="{{ asset('assets/css/plugins/jquery/jquery.min.js') }}" type="text/javascript"></script>
    <!-- Bootstrap Core Js -->
    <!-- <script src="{{ asset('assets/css/plugins/bootstrap/js/bootstrap.js') }}" type="text/javascript"></script> -->
    <!-- Select Plugin Js -->
    <!-- <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script> -->
    <script src="{{ asset('assets/css/plugins/bootstrap-select/js/bootstrap-select.js') }}" type="text/javascript"></script>

    <!-- Slimscroll Plugin Js -->
    <!-- <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script> -->
    <script src="{{ asset('assets/css/plugins/jquery-slimscroll/jquery.slimscroll.js') }}" type="text/javascript"></script>

    <!-- Waves Effect Plugin Js -->
    <!-- <script src="../../plugins/node-waves/waves.js"></script> -->
    <script src="{{ asset('assets/css/plugins/node-waves/waves.js') }}" type="text/javascript"></script>

    <!-- Autosize Plugin Js -->
    <!-- <script src="../../plugins/autosize/autosize.js"></script> -->
    <script src="{{ asset('assets/css/plugins/autosize/autosize.js') }}" type="text/javascript"></script>


    <!-- Moment Plugin Js -->
    <!-- <script src="../../plugins/momentjs/moment.js"></script> -->
    <script src="{{ asset('assets/css/plugins/momentjs/moment.js') }}" type="text/javascript"></script>




    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ asset('assets/css/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}" type="text/javascript"></script>
    
    <!-- Custom Js -->
    <!-- <script src="{{ asset('assets/js/admin.js') }}" type="text/javascript"></script> -->
    <script src="{{ asset('assets/js/pages/forms/basic-form-elements.js')}}" type="text/javascript"></script>


    
@endsection

resources/views/Customers/edit.blade.php
@extends('layouts.sidebar')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" />
@endsection

@section('section')
<section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>
                    CUSTOMERS
                    
                </h2>
            </div>
            
            <!-- Advanced Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>EDIT CUSTOMER</h2>
                            
                        </div>
                        <div class="body">
                            <form action="{{ route('customer.update',$id) }}" enctype="multipart/form-data" method="post"> 
                                <input name="_method" type="hidden" value="PATCH">
                                {{ csrf_field() }}
                                

                                
                                
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="name" id="name"  minlength="5" maxlength="191" value="{{ $name }}" required>
                                        <label class="form-label">Name</label>
                                    </div>
                                    <div class="help-info">Min. 5 characters</div>
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span><br>
                                    @endif
                                </div>

                                

                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control" name="contact" id="contact"  minlength="5" maxlength="191" value="{{ $contact }}" required>
                                        <label class="form-label">Added by</label>
                                    </div>
                                    <div class="help-info">Min. 5 characters</div>
                                    @if ($errors->has('contact'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('contact') }}</strong>
                                        </span><br>
                                    @endif
                                </div>
                                
                                
                                
                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Advanced Validation -->
            
        </div>
    </section>

@endsection

@section('script')

   <!-- Jquery Core Js -->
    <script src="{{ asset('assets/css/plugins/jquery/jquery.min.js') }}" type="text/javascript"></script>
    <!-- Bootstrap Core Js -->
    <!-- <script src="{{ asset('assets/css/plugins/bootstrap/js/bootstrap.js') }}" type="text/javascript"></script> -->
    <!-- Select Plugin Js -->
    <!-- <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script> -->
    <script src="{{ asset('assets/css/plugins/bootstrap-select/js/bootstrap-select.js') }}" type="text/javascript"></script>

    <!-- Slimscroll Plugin Js -->
    <!-- <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script> -->
    <script src="{{ asset('assets/css/plugins/jquery-slimscroll/jquery.slimscroll.js') }}" type="text/javascript"></script>

    <!-- Waves Effect Plugin Js -->
    <!-- <script src="../../plugins/node-waves/waves.js"></script> -->
    <script src="{{ asset('assets/css/plugins/node-waves/waves.js') }}" type="text/javascript"></script>

    <!-- Autosize Plugin Js -->
    <!-- <script src="../../plugins/autosize/autosize.js"></script> -->
    <script src="{{ asset('assets/css/plugins/autosize/autosize.js') }}" type="text/javascript"></script>


    <!-- Moment Plugin Js -->
    <!-- <script src="../../plugins/momentjs/moment.js"></script> -->
    <script src="{{ asset('assets/css/plugins/momentjs/moment.js') }}" type="text/javascript"></script>




    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ asset('assets/css/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}" type="text/javascript"></script>
    
    <!-- Custom Js -->
    <!-- <script src="{{ asset('assets/js/admin.js') }}" type="text/javascript"></script> -->
    <script src="{{ asset('assets/js/pages/forms/basic-form-elements.js')}}" type="text/javascript"></script>


    
@endsection

resources/views/Customers/menu.blade.php
@extends('layouts.sidebar')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" />
@endsection

@section('section')
<section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>
                    TRANSACTION
                    
                </h2>
            </div>
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                INVENTORIES
                            </h2>
                            <ul class="header-dropdown m-r--4">
                               <a href="{{ route('customer.create') }}">
                                    <button class="btn btn-primary btn-sm"><i class="material-icons" style="color:white;">add_box</i></button>
                                </a>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th width="150px">Name</th>
                                            <th>Contact</th>
                                            <th width="130px">Action</th>
                                        </tr>
                                    </thead>
                                    
                                        @foreach($customer as $ex)
                                        <tr>
                                            
                                            <td>{{ $ex->name }}</td>
                                            <td>{{ $ex->contact }}</td>
                                            
                                           
                                            <td>
                                                

                                                <a href="{{ route('customer.edit', $ex->id) }}">
                                                    <button class="btn btn-warning btn-sm" title='Edit data'><i class="material-icons">edit</i></button>
                                                </a>
                                                
                                                
                                                
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
            
        </div>

    </section>


@endsection

@section('script')
<script>
function myFunction() {
    alert("Testing sections!");
}
</script>
    
    <!-- Jquery Core Js -->
    <script src="{{ asset('assets/css/plugins/jquery/jquery.min.js') }}" type="text/javascript"></script>
    <!-- <script src="../../plugins/jquery/jquery.min.js"></script> -->

    <!-- Bootstrap Core Js -->
    <!-- <script src="{{ asset('assets/css/plugins/bootstrap/js/bootstrap.js') }}" type="text/javascript"></script> -->
    <!-- <script src="../../plugins/bootstrap/js/bootstrap.js"></script> -->
   
    <!-- Select Plugin Js -->
    <!-- <script src="../../plugins/bootstrap-select/js/bootstrap-select.js"></script> -->
    <!-- <script src="{{ asset('assets/css/plugins/bootstrap-select/js/bootstrap-select.js') }}" type="text/javascript"></script> -->

    <!-- Slimscroll Plugin Js -->
    <!-- <script src="../../plugins/jquery-slimscroll/jquery.slimscroll.js"></script> -->
    <script src="{{ asset('assets/css/plugins/jquery-slimscroll/jquery.slimscroll.js') }}" type="text/javascript"></script>

    <!-- Waves Effect Plugin Js -->
    <!-- <script src="../../plugins/node-waves/waves.js"></script> -->
    <script src="{{ asset('assets/css/plugins/node-waves/waves.js') }}" type="text/javascript"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/css/plugins/jquery-datatable/jquery.dataTables.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/extensions/export/jszip.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}" type="text/javascript"></script>

    <!-- Custom Js -->
    <script src="{{ asset('assets/js/pages/tables/jquery-datatable.js') }}" type="text/javascript"></script>

@endsection