routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {

    return view('index');
})->name('login');

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/login', 'LoginController@login');
Route::post('/logout', 'LoginController@logout')->name('logout');

Route::resource('User/orderh', 'OrderHeaderCRUDController');
Route::resource('User/orderd', 'OrderDetailCRUDController');
Route::resource('User/expenditure', 'ExpenditureCRUDController');
Route::resource('User/inventory', 'InventoryCRUDController');
Route::resource('User/customer', 'CustomerCRUDController');

Route::get('User/orderd/create/{id}','OrderDetailCRUDController@createOrderD')->name('orderd.create.orderd');
Route::post('User/orderd/store/{id}','OrderDetailCRUDController@storeOrderD')->name('orderd.store.orderd');
Route::get('User/orderd/edit/{id_order_h}/{orderd}','OrderDetailCRUDController@editOrderD')->name('orderd.edit.orderd');
Route::patch('User/orderd/update/{id_order_h}/{orderd}','OrderDetailCRUDController@updateOrderD')->name('orderd.update.orderd');
Route::delete('User/orderd/destroy/{id_order_h}/{orderd}','OrderDetailCRUDController@destroyOrderD')->name('orderd.destroy.orderd');
Route::post('User/pdf','PDFController@pdf')->name('pdf');
Route::get('User/recap','PDFController@index')->name('recap');
Route::get('User/orderd/index/{id}','OrderDetailCRUDController@indexOrderD')->name('orderd.index.orderd');
Route::post('User/orderd/index/{id}','OrderDetailCRUDController@indexOrderD')->name('orderd.index.orderd');

resources/views/layouts/plane.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>LevvelApp</title>
    <!-- Favicon-->
    <link rel="shortcut icon" href="{{ asset('assets/image/favicon/apple-icon-57x57.png') }}">
    <!-- Favicon -->   
    <link rel="apple-touch-icon" type="image/png" sizes="57x57" href="{{ asset('/image/favicon/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="60x60" href="{{ asset('/image/favicon/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="72x72" href="{{ asset('/image/favicon/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="76x76" href="{{ asset('/image/favicon/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="114x114" href="{{ asset('/image/favicon/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="120x120" href="{{ asset('/image/favicon/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="144x144" href="{{ asset('/image/favicon/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="152x152" href="{{ asset('/image/favicon/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" type="image/png" sizes="180x180" href="{{ asset('/image/favicon/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" type="image/png" sizes="192x192"  href="{{ asset('/image/favicon/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" type="image/png" sizes="32x32" href="{{ asset('/image/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" type="image/png" sizes="96x96" href="{{ asset('/image/favicon/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" type="image/png" sizes="16x16" href="{{ asset('/image/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" type="image/png" content="{{ asset('/image/favicon/ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">
    <!-- /Favicon -->
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- /  Google fonts -->
    <!-- Bootstrap Core Css -->
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/bootstrap/css/bootstrap.css') }}" />

    <!-- Waves Effect Css -->
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/node-waves/waves.css') }}" />
    
    <!-- Animation Css -->
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/animate-css/animate.css') }}" />
    <!-- Morris Chart Css-->
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/morrisjs/morris.css') }}" />
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" />
    <!-- AdminBSB Themes-->
    <link rel="stylesheet" href="{{ asset('assets/css/themes/all-themes.css') }}" />
    <!-- Font Awesome Icons-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    @yield('style')
    
</head>

<body class="theme-red">
    <!-- Page Loader -->
    
    @yield('body')
    
    <!-- Jquery Core Js -->
    <script src="{{ asset('assets/css/plugins/jquery/jquery.min.js') }}" type="text/javascript"></script>
     <!-- Bootstrap Core Js -->
    <script src="{{ asset('assets/css/plugins/bootstrap/js/bootstrap.js') }}" type="text/javascript"></script>
     <!-- Select Plugin Js -->
    <script src="{{ asset('assets/css/plugins/bootstrap-select/js/bootstrap-select.js') }}" type="text/javascript"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('assets/css/plugins/jquery-slimscroll/jquery.slimscroll.js') }}" type="text/javascript"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('assets/css/plugins/node-waves/waves.js') }}" type="text/javascript"></script>
   
   
    <!-- Jquery CountTo Plugin Js -->
    <script src="{{ asset('assets/css/plugins/jquery-countto/jquery.countTo.js') }}" type="text/javascript"></script>
    <!-- Morris Plugin Js -->
    <script src="{{ asset('assets/css/plugins/raphael/raphael.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/morrisjs/morris.js') }}" type="text/javascript"></script>

    <!-- ChartJs -->
    <script src="{{ asset('assets/css/plugins/chartjs/Chart.bundle.js') }}" type="text/javascript"></script>

    <!-- Flot Charts Plugin Js -->
    <script src="{{ asset('assets/css/plugins/flot-charts/jquery.flot.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/flot-charts/jquery.flot.resize.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/flot-charts/jquery.flot.pie.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/flot-charts/jquery.flot.categories.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/css/plugins/flot-charts/jquery.flot.time.js') }}" type="text/javascript"></script>
    @yield('script')
    <!-- Sparkline Chart Plugin Js -->
    <script src="{{ asset('assets/css/plugins/jquery-sparkline/jquery.sparkline.js') }}" type="text/javascript"></script>

    <!-- Custom Js -->
    <script src="{{ asset('assets/js/admin.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/pages/index.js') }}" type="text/javascript"></script>

    <!-- Demo Js -->
    <!-- <script src="js/demo.js"></script> -->
    <script src="{{ asset('assets/plugins/jquery-countto/jquery.countTo.js') }}" type="text/javascript"></script>
    <script src="http://maps.google.com/maps/api/js"></script>

    <!-- Google Maps Key-->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKS6IWjM2MdnawgG1PrJjq93wQTlWb1Ys&callback=initMap">
    </script>
    
</body>

</html>

resources/views/layouts/sidebar.blade.php
@extends('layouts.plane')
@section('body')

<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>
<!-- #END# Page Loader -->
<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- #END# Overlay For Sidebars -->
<!-- Search Bar -->
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>
<!-- #END# Search Bar -->
<!-- Top Bar -->
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ url ('') }}">
                <div style="padding:0px;margin-top:-16px;margin-left:0px;">
                    <img src= "{{ asset('assets/image/levvel.png') }}" alt="Levvel" width="53px" style="display: inline-block;">
                    

                    <!-- <span style="display: inline-block; margin-left:5px;">VTal Admin</span> -->
                </div>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <!-- <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li> -->
                <!-- #END# Call Search -->
                <!-- Notifications -->
                <!-- <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">notifications</i>
                        <span class="label-count">7</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">NOTIFICATIONS</li>
                        <li class="body">
                            <ul class="menu">
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">person_add</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>12 new members joined</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 14 mins ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-cyan">
                                            <i class="material-icons">add_shopping_cart</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>4 sales made</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 22 mins ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-red">
                                            <i class="material-icons">delete_forever</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>Nancy Doe</b> deleted account</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 3 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-orange">
                                            <i class="material-icons">mode_edit</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>Nancy</b> changed name</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 2 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-blue-grey">
                                            <i class="material-icons">comment</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>John</b> commented your post</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 4 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">cached</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>John</b> updated status</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 3 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-purple">
                                            <i class="material-icons">settings</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>Settings updated</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> Yesterday
                                            </p>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="javascript:void(0);">View All Notifications</a>
                        </li>
                    </ul>
                </li> -->
                <!-- #END# Notifications -->
                
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
            </ul>
        </div>
    </div>
</nav>
<!-- #Top Bar -->
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <!-- <div class="image">
                

            </div> -->
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome,</div>
                <div class="email">{{auth('')->user()->name}}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li role="seperator" class="divider"></li>
                        
                        <li><a href="{{ route('logout') }}"><i class="material-icons">input</i>Sign Out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            <ul class="list">
                <li class="header">NAVIGATION</li>
                <li class="active">
                    <a href="{{ route('orderh.index') }}">
                        <i class="material-icons">home</i>
                        <span>Home</span>
                    </a>
                </li>
                
                <li class="header">TRANSACTION</li>
                    
                    
                    <li>
                        <a href="{{ route('orderh.index') }}">
                            <i class="material-icons">local_mall</i>
                            <span>Orders</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('inventory.index') }}">
                            <i class="material-icons">work</i>
                            <span>Inventory</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('expenditure.index') }}">
                            <i class="material-icons">local_offer</i>
                            <span>Expenditures</span>
                        </a>
                    </li>
                        
                </li>
                <li class="header">CUSTOMERS</li>
                    
                    
                    <li>
                        <a href="{{ route('customer.index') }}">
                            <i class="material-icons">contacts</i>
                            <span>Contacts</span>
                        </a>
                    </li>
                    
                        
                </li>
                    
                @if (auth()->user()->can('view.cia'))
                <li class="header">RECAP</li>
                <li>
                    <a href="{{ route('recap') }}">
                        <i class="material-icons">file_download</i>
                        <span>Download Recap</span>
                    </a>
                </li>
                @endif
                        
                </li>
            </ul>
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; 2018 <a href="javascript:void(0);">Levvel</a>.
            </div>
            <div class="version">
                <b>Version: </b> 1.0.0
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">
        
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active in active" id="settings">
                <div class="demo-settings">
                    <p>MENU</p>
                    <ul class="setting-list" style="text-align:center;">

                        <li>
                            <a href="{{ route('orderh.index') }}">
                                <span><i class="material-icons">person</i>Profile</span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('logout') }}">
                                <span><i class="material-icons">input</i>Sign Out</span>
                            </a>
                        </li>
                        
                        
                    </ul>
                    
                </div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="settings">
                
            </div>
        </div>
    </aside>
    <!-- #END# Right Sidebar -->
</section>

@yield('section')
@endsection